### ISSUE TITLE
Relative link to wp-json

### ISSUE THREAD

**Issue by edent** [stefanbohacek/fediverse-embeds-wordpress-plugin#10]
Images don't show because my blog is installed in `/blog` rather than the root directory.

The plugin tries to show my avatar at `/wp-json/ftf/media-proxy?url=https://files.mastodon.social/accounts/avatars/000/007/112/original/37df032a5951b96c.jpg`

But it should be `/blog/wp-json/ftf/media-proxy?url=https://files.mastodon.social/accounts/avatars/000/007/112/original/37df032a5951b96c.jpg`

**Comment by edent** [comment]
Found in:

* https://github.com/stefanbohacek/fediverse-embeds-wordpress-plugin/blob/main/src/frontend/scripts/renderPost.js
* https://github.com/stefanbohacek/fediverse-embeds-wordpress-plugin/blob/main/src/frontend/scripts/processPosts.js

Because they're .js, you can't use [`get_site_url()`](https://developer.wordpress.org/reference/functions/get_site_url/)

**Comment by stefanbohacek** [comment]
Thank you for reporting this! Should be fixed with https://github.com/stefanbohacek/fediverse-embeds-wordpress-plugin/commit/bf4eb56a30c8f42f0a553ec6d829053e6db94abc.

**Comment by edent** [comment]
Yup!
