### ISSUE TITLE
CSS Weirdness

### ISSUE THREAD

**Issue by edent** [stefanbohacek/fediverse-embeds-wordpress-plugin#12]
This is odd.  The plugin is correctly loading `/dist/css/styles-bs.min.css` and applying the styles. But it doesn't seem to like *any* of the CSS variables. 
![Screenshot of CSS errors](https://github.com/stefanbohacek/fediverse-embeds-wordpress-plugin/assets/837136/e28c187e-44c4-46d6-99ef-24fd03b4b8fb)

**Comment by stefanbohacek** [comment]
Fixed with https://github.com/stefanbohacek/fediverse-embeds-wordpress-plugin/commit/0f4d4ec37e1f01aeb0009de9363bcfd742dbf46e.
