### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by morphtown** [stefanbohacek/fediverse-embeds-wordpress-plugin#13]
WordPress version 6.2.2
Active theme: Twenty Twenty-Three (version 1.1)
Current plugin: Fediverse Embeds (version 1.0.0)
PHP version 8.0.26

Error Details
=============
An error of type E_ERROR was caused in line 60 of the file /var/www/.../wp-content/plugins/fediverse-embeds-wordpress-plugin-main/includes/Helpers.php. Error message: Uncaught TypeError: log(): Argument #1 ($num) must be of type float, string given in /var/.../wp-content/plugins/fediverse-embeds-wordpress-plugin-main/includes/Helpers.php:60
Stack trace:
#0 /var/www/.../wp-content/plugins/fediverse-embeds-wordpress-plugin-main/includes/Helpers.php(60): log()
#1 /var/www/.../wp-content/plugins/fediverse-embeds-wordpress-plugin-main/includes/Helpers.php(53): FTF_Fediverse_Embeds\Helpers::format_bytes()
#2 /var/www/.../wp-content/plugins/fediverse-embeds-wordpress-plugin-main/includes/Settings.php(184): FTF_Fediverse_Embeds\Helpers::get_directory_size()
#3 /var/www/.../wp-admin/includes/template.php(1773): FTF_Fediverse_Embeds\Settings->render_settings_form()
#4 /var/www/.../wp-content/plugins/fediverse-embeds-wordpress-plugin-main/includes/Settings.php(50): do_settings_sections()
#5 /var/www/.../wp-includes/class-wp-hook.php(308): FTF_Fediverse_Embeds\Settings->render_settings_page()
#6 /var/www/.../wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#7 /var/www/.../wp-includes/plugin.php(517): WP_Hook->do_action()
#8 /var/www/.../wp-admin/admin.php(259): do_action()
#9 /var/www/.../options-general.php(10): require_once('...')
#10 {main}
  thrown

**Comment by stefanbohacek** [comment]
@morphtown Thank you for filing the issue, this should be fixed now. Mind giving it another try?
