### ISSUE TITLE
Plugin crashes Twenty Twenty Four Navigation

### ISSUE THREAD

**Issue by barning** [stefanbohacek/fediverse-embeds-wordpress-plugin#28]
When activating this plugin with the Twenty Twenty Four Theme enabled,`TypeError: Failed to resolve module specifier "@wordpress/interactivity". Relative references must start with either "/", "./", or "../".` crashes the mobile navigation of the theme.

**Comment by stefanbohacek** [comment]
@barning Thank you for reporting this, will investigate!

**Comment by stefanbohacek** [comment]
Same issue as https://github.com/WordPress/performance/issues/1083, fixed with https://github.com/stefanbohacek/fediverse-embeds-wordpress-plugin/commit/6789afee7678c05622d6814110fbb856734c7a37.
